# $Id: Makefile,v 1.12 2007/02/20 21:24:32 amotin Exp $

.NOTPARALLEL:

all:		mpd.8

DOC=		mpd
FORMATS=	html ps

SRCS+=		mpd.sgml version.sgml
SRCS+=		overview.sgml layers.sgml manorg.sgml changes.sgml
SRCS+=		getting.sgml building.sgml installing.sgml
SRCS+=		invoke.sgml configfmt.sgml cli.sgml
SRCS+=		gencmd.sgml global.sgml console.sgml web.sgml bundle.sgml repeater.sgml 
SRCS+=		interface.sgml links.sgml ipcp.sgml compression.sgml encryption.sgml
SRCS+=		modem.sgml nat.sgml netgraph.sgml tcp.sgml udp.sgml pptp.sgml l2tp.sgml pppoe.sgml
SRCS+=		chat.sgml trouble.sgml refs.sgml int-auth.sgml todo.sgml netflow.sgml

CLEANFILES+=	version.sgml mpd.8 mpd.ps

.SUFFIXES:	.in

.in:
	VERSION=`grep ^VERSION= ../src/Makefile | awk '{ print $$2 }'`; \
	DATE=`date +'%B %e, %Y`; \
	sed \
	  -e "s/@DATE@/$$DATE/g" \
	  -e "s/@VERSION@/$$VERSION/g" \
	  < ${.ALLSRC} > ${.TARGET}

.include "bsd.sgml.mk"
