# $Id: Makefile,v 1.1 2001/03/10 06:06:47 archiecobbs Exp $

.NOTPARALLEL:

all:		mpd.8

DOC=		mpd
FORMATS=	html

SRCS+=		mpd.sgml version.sgml
SRCS+=		overview.sgml layers.sgml manorg.sgml changes.sgml
SRCS+=		getting.sgml building.sgml installing.sgml
SRCS+=		invoke.sgml configfmt.sgml cli.sgml
SRCS+=		gencmd.sgml bundle.sgml interface.sgml links.sgml
SRCS+=		ipcp.sgml compression.sgml encryption.sgml
SRCS+=		modem.sgml netgraph.sgml tcp.sgml udp.sgml pptp.sgml pppoe.sgml
SRCS+=		chat.sgml
SRCS+=		refs.sgml

CLEANFILES+=	version.sgml mpd.8

.SUFFIXES:	.in

.in:
	VERSION=`grep ^VERSION= ../src/Makefile | awk '{ print $$2 }'`; \
	DATE=`date +'%B %e, %Y`; \
	sed \
	  -e "s/@DATE@/$$DATE/g" \
	  -e "s/@VERSION@/$$VERSION/g" \
	  < ${.ALLSRC} > ${.TARGET}

.include <bsd.sgml.mk>
